version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: guzellix
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass

    ports:
      - "5461:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/guzellix
      - SONAR_JDBC_USERNAME=root
      - SONAR_JDBC_PASSWORD=pass
    depends_on:
      - postgres
volumes:
  db_data: